### ISSUE TITLE
Header should only be sent to next slot proposer after authentication to avoid non-sealed auction

### ISSUE THREAD

**Issue by Ruteri** [flashbots/mev-boost#102]
If anyone but given slot's proposer is allowed to call `builder_getHeader` and receive best header, the header auction is no longer sealed and builders will try and bid for the lowest possible transfer to the proposer.

Only proposer for the given slot should be able to call `builder_getHeader`, this ensures sealed bid as long as relay can be trusted (is not submitting the bids off chain).

**Comment by metachris** [comment]
Implications:
1.`builder_getHeader` must include a signature by the validator
2. the builder must return an error if the request doesn't contain a valid signature by the proposer of that slot

**Comment by lightclient** [comment]
It seems unlikely that we'll continue relying on a direct line of communication between the validator and relay/builder in short/medium term, therefore the bids will be available on the p2p network. We might be able to avoid that by encrypting them to the proposer.

This is because we want to defend against relays withholding blocks after the validator signs the header, and the only way this is possible is if the `mev-boost` network i) observes the relay's solicitation of the proposer via a bid for including a certain header, ii) observes the signed blind beacon block from the proposer and iii) observes the _absence_ of the relay's unblinded header. Without any of these steps, the network cannot attribute the fault to either the validator or the relay.

In the long term, PBS will require builders to gossip bids so that proposer can pick the best one. With SSLE, the network won't even know who the next proposer will be.

With that said -- we may _have_ to sign the `GetHeader` request in a p2p context to avoid spam.

**Comment by obadiaa** [comment]
related issue #112

**Comment by metachris** [comment]
Should we close this in favor of #112?

**Comment by metachris** [comment]
Closed in favor of https://github.com/flashbots/mev-boost/issues/112
