### ISSUE TITLE
How can I know how the reward is sent from the builder to the validator?

### ISSUE THREAD

**Issue by lurais** [flashbots/mev-boost#407]
Hello,I'm very interested in the relationship between builders and validators, and would like to know how the reward is distributed, say through a transaction or a contract? Where can I find information about how rewards are distributed?Is there any detail description about the code implementation?

**Comment by ralexstokes** [comment]
builders are free to pay validators in whatever way they wish

there is a soft norm amongst the community so far to use the **last** transaction of a block as a payment transaction from the builder to the proposer

I don't think this is formally spec'd anywhere yet

**Comment by lurais** [comment]
> builders are free to pay validators in whatever way they wish
> 
> there is a soft norm amongst the community so far to use the **last** transaction of a block as a payment transaction from the builder to the proposer
> 
> I don't think this is formally spec'd anywhere yet

thanks , I am very interested in this，Is there a detailed documentation on this soft norm for newer to refer? The points I care about are: 
1. How to ensure that the block given by the builder will be paid to the validator after being proposed? 
2. How to ensure that the validator will propose the builder's block after obtaining the builder's amount? 
3. What is the role of relay? What happens without relay?
4. How does pbs solve the problem of centralization?

**Comment by ralexstokes** [comment]
> How to ensure that the block given by the builder will be paid to the validator after being proposed?

right now, validators trust builders/relays that they pay the amount they claim; there is research into payment proofs to remove this trust assumption

> How to ensure that the validator will propose the builder's block after obtaining the builder's amount?

in the current construction the validator cannot get the builder's payment until they have committed to the builder's block and moreover builders/relays have enough information once they get a validator's acceptance of a bid to publish the full block themselves

refer to the builder-specs: https://github.com/ethereum/builder-specs for more info

> What is the role of relay? What happens without relay?

relays are a necessary, trusted component of the current design to facilitate interaction b/t mutually untrusting builders and proposers -- if a given validator trusts a given builder to not abuse them in any way then that validator can peer directly with the builder

> How does pbs solve the problem of centralization?

PBS aims to address validator centralization by removing any additional requirement for validators to also specialize in building valuable blocks so that validators can remain competitive amongst other validators with no additional effort

**Comment by lurais** [comment]
> > How does pbs solve the problem of centralization?
> 
> PBS aims to address validator centralization by removing any additional requirement for validators to also specialize in building valuable blocks so that validators can remain competitive amongst other validators with no additional effort

but will it cause the problem of builder centralization? As competitive builders will win more reward.
