### ISSUE TITLE
Removing of Docker image tag "latest-portable"

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#422]
On Docker hub, the `latest` tag is currently the portable build (since v1.4.0): https://hub.docker.com/r/flashbots/mev-boost/tags

There is still, however, an old and not updated `latest-portable` tag, which was last updated 2 months ago. 

Let's remove the `latest-portable` tag, because it's misleading and not needed anymore.

It might lead to existing integrations that use this tag to break. Although production deployments should usually reference a specific version instead of `latest`, and I believe the impact is negligible.

**Comment by dc25** [comment]
I've been using the `latest-portable` tag to get a version of mev-boost that runs on my laptop which is something like 8 years old and can't run the code built using the `latest ` tag.

This is per suggestion in eth-docker :  see line 130 of https://github.com/eth-educators/eth-docker/blob/main/default.env .

Of course this broke recently because the latest-portable tag was not updated.

Right now I'm specifying 1.4.0-portable but that has to be maintained by hand.

Is there another (better?) way to handle this (other than getting a new computer)?

**Comment by metachris** [comment]
Why can't you run the `latest` tag? The resource usage should be identical to the previous version, and it's the portable build.

**Comment by dc25** [comment]
Indeed I can do exactly that.    Should have read earlier comments more carefully.   Thank you for responding.

**Comment by metachris** [comment]
removed the `latest-portable` docker image from docker hub.
