### ISSUE TITLE
MEV-Boost logs 500x responses at info level

### ISSUE THREAD

**Issue by screwyprof** [flashbots/mev-boost#443]
In the logs, when a relay returns a non 200 http code we can see two lines related to the same query. The first line logged  by the endpoint itself and correctly marked as an error:

```json
{
   "error":"Get \"https://builder-relay-goerli.flashbots.net/eth/v1/builder/status\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)",
   "level":"error",
   "msg":"relay status error - request failed",
   "time":"2023-02-03T03:32:36Z",
   "url":"https://builder-relay-goerli.flashbots.net/eth/v1/builder/status",
}
```

The second is logged by the middleware which always uses `Info` level, no matter the status.
```json
{
   "duration":"0.950913",
   "level":"info",
   "method":"GET",
   "msg":"http: GET /eth/v1/builder/status 503",
   "path":"/eth/v1/builder/status",
   "status":503,
   "time":"2023-02-03T03:32:36Z",
}
```

This behaviour is confusing. It would be great if the middleware could check the returned status codes and log the result with the corresponding level.

Also it would make more sense if the first message was logged at `Debug` or `Warning` level as it doesn't lead to a `mev-boost` status endpoint error if there is at least one working relay.

![Screenshot 2023-02-03 at 15 27 54](https://user-images.githubusercontent.com/1536274/216642086-609105ac-2ca3-43a7-9432-dacd3353fb33.png)

**Comment by metachris** [comment]
To have the HTTP request information logged as INFO is expected behaviour, and I don't think a HTTP logging middleware should change the loglevel based on the status code. In particular since any message logged with error level should be immediately investigated by the engineering/devops team, and the HTTP logging middleware just doesn't have enough context to decide which is actually an error to investigate versus not.
