### ISSUE TITLE
Liveness endpoint

### ISSUE THREAD

**Issue by realbigsean** [flashbots/mev-boost#60]
Is it possible to add something like a liveness endpoint we could poll with more frequency?

**Comment by metachris** [comment]
Are you thinking a HTTP endpoint like `/health` or a specific JSON-RPC method?

**Comment by realbigsean** [comment]
We use the `eth_syncing` JSON-RPC endpoint as a proxy for execution layer liveness, so I was imagining something similar. It'd probably be easiest to use JSON-RPC here because it's used elsewhere in this API

**Comment by metachris** [comment]
Would you have a specific proposal for the API (method, response)?

**Comment by metachris** [comment]
The only question is about naming, and which response. Did we leave the workshop with the consensus that a JSON-RPC call is fine?

If so, we could call the method mevboost_health or mevboost_status perhaps, and the response be just true for now? I feel like reusing the builder namespace isn't great, because it's literally querying the mevgeth status, not the builder status 🤔

**Comment by metachris** [comment]
Proposal: `builder_status`: https://github.com/ethereum/execution-apis/pull/209/files#diff-20ad1b5e044517450181107c321127eff3a6beeb9deaee4906c9c90cc778daf9R256

**Comment by metachris** [comment]
implemented in the current master branch of mev-geth (also v0.3.0+): https://github.com/flashbots/mev-boost/blob/main/server/service.go#L301
