### ISSUE TITLE
Discussion: should mev-boost poll the relays?

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#65]
The original spec had as step 3 "mev-boost begins polling connected relays for their [SignedMEVPayloadHeader](https://github.com/flashbots/mev-boost/wiki/Specification/2890a0dc80817031da0e58183d8a63a341a42e73#signedmevpayloadheader) using [relay_getPayloadHeaderV1](https://github.com/flashbots/mev-boost/wiki/Specification/2890a0dc80817031da0e58183d8a63a341a42e73#relay_getpayloadheaderv1) requests."

The current implementation does not poll, just when it receives builder_getPayloadHeaderV1 it queries all the relays. We removed the polling now from the spec, but want to open an issue for discussion.

**Comment by jparyani** [comment]
After some discussion with @metachris, we came up with the following design:

* add a new endpoint to relays, `relay_getPayloadHeaders`, which returns a list of potential payloads built on top of different head states
* mev-boost would poll this endpoint across all relays
* when `builder_getPayloadHeader` is called, mev-boost would return the most profitable payload built on top of the given blockHash from the local cache of responses from `relay_getPayloadHeaders`

The upside of this design is guaranteed quick calls for `builder_getPayloadHeader`, whereas under the current proposal we’ll always have to wait for the slowest relay. The main downside I see is added complexity and a latency penalty depending on the polling interval. This could perhaps be solved by moving from polling to instead having relays push payloads (eg. over a websocket).

If we ended up keeping forkChoiceUpdated or added a new endpoint like `preparePayload` to signal what block to build on, then we wouldn’t need `relay_getPayloadHeaders`, but I’m not sure it’s worth it. As far as relays are concerned, they’ll be building across multiple likely head states anyways, so signaling which one a validator wants isn’t super important.

**Comment by metachris** [comment]
How would the polling for a specific validator would be initiated? Would mev-boost poll constantly (always), or would the CL client signal to mev-boost that it should start polling at a specific point-in-time?

**Comment by lightclient** [comment]
* I definitely think relays should be aware of what validator is expected to propose at what slot. Therefore they should only be preparing headers for _that_ validator.
* If we think about the current engine API flow for block construction, i) first the CL updates the EL fork choice. As part of that, it ii) also notes that it would like the EL to begin building a block for the next slot. Then at some later point, iii) the CL requests the block that the EL has been building. If we map this to the interface here, we should be able to skip the first two steps. This is because the relay is aware of all competing forks for a certain slot, and it will begin it's building process immediately after observing a new block. So in that case, it makes sense to me that the CL would ask `mev-boost` once when it's ready for a block. It would be good to have a suggested upper bound of time which that request would be expected to take, but at the end of the day, the CL needs to decide if things are taking too long and get a block locally if they are.

**Comment by metachris** [comment]
Closing this for now, we'll start with the flow described in the [spec](https://github.com/flashbots/mev-boost/blob/main/docs/specification.md) and may revisit polling or pushing at a later date.
