### ISSUE TITLE
Break out future goals from #34 (milestone 2 PR)

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#89]
Create new issues for future goals, including those formulated in #34, in particular [milestone2.md](https://github.com/flashbots/mev-boost/blob/895e6c57baf48a5eb5fbd64150c5b5d1f2b93347/docs/milestone-2.md)

Those include:
1. Merkle proof of payment (see [milestone-2.md#accountproof](https://github.com/flashbots/mev-boost/blob/895e6c57baf48a5eb5fbd64150c5b5d1f2b93347/docs/milestone-2.md#accountproof))
1. Payload validity fraud proof (see #88 )
1. ~Validator authentication (partly covered with `setFeeRecipient` in [current v0.2 spec](https://github.com/flashbots/mev-boost/blob/main/docs/specification.md). Perhaps open is how to allow multiple validators use one CL client 🤔 )~

Maybe more / others 

🙏

**Comment by lightclient** [comment]
* Multiple validators using the same CL -- what issue do you envision here? CL clients currently support multiple validators connected to a single beacon node. With respect to builders, since we've shifted the burden to them to know which validator is proposing at what slot, I think it will just be up to the beacon node to decide if the `feeRecipient` was set appropriately?
* Merkle proof payment -- can you elaborate on what sort of scheme this might be? Would this be a proof provided with the header to a transaction that transfers `ETH` to the validator's `feeRecipient`?
* Payload validity fraud proof -- I feel like specifying a p2p network should take precedence over this. I don't think it makes sense for this to be a part of the synchronous Builder API, because the value of the fraud proof is to share with others. Of course, we could allow relays to disseminate the information, however that feels like a side quest to preferred approach.
* p2p builder network -- the synchronous Builder API is a great stepping stone and interface for CL <> mev-boost, but it has serious drawbacks w.r.t. privacy. I personally think we should do everything in our power to make sure we go into the merge with a proper p2p network around mev-boost that improves this situation. Eventually, it would be great to integrate this p2p network into the CL networking stack. However, I don't think this is a tenable approach if we hope to have a p2p network at the moment of the merge. I think our best bet is to use an off-the-shelf stack (I'm partial to discv5 + devp2p because it is what I am most familiar with) and create a bespoke subnet for mev-boost communication. That would essentially entail turning the Builder API messages as we have them into p2p messages, defining some propagation semantics, and adding in some fault attribution logic + messages (e.g. "I saw validator X send a signed header, but never saw the relay unblind the block behind it. I'll stop using them" or "I just received conflicting signed messages from a relay, they must be doing something malicious. I'll stop using them."

**Comment by metachris** [comment]
> Multiple validators using the same CL ...

Yes, I think this is not an issue anymore. With the current design multiple validators can use one CL client without conflicts.

---

@thegostep @jparyani any thoughts on the other points here?
